standalone:
	$(MAKE) -C example_standalone

shared:
	$(MAKE) -C example_shared

install_standalone:
	$(MAKE) install -C example_standalone

install_shared:
	$(MAKE) install -C example_shared

clean_shared:
	$(MAKE) clean_all -C example_shared

clean_standalone:
	$(MAKE) clean -C example_standalone