x-common-attrs: &common-attrs
  volumes:
    - ..:/hwcpipe2
  working_dir: /hwcpipe2

services:
  hwcpipe2:
    container_name: hwcpipe2
    image: gpuddk--docker.artifactory.geo.arm.com/gpuddk/hwcpipe2:latest
    build:
      target: hwcpipe2-final
      args:
        BASE_ENV_IMAGE: hwcpipe2-dev
    <<: *common-attrs
  hwcpipe2-pre-commit:
    container_name: hwcpipe2-pre-commit
    image: gpuddk--docker.artifactory.geo.arm.com/gpuddk/hwcpipe2-pre-commit:latest
    build:
      target: hwcpipe2-final
      args:
        BASE_ENV_IMAGE: hwcpipe2-pre-commit
    <<: *common-attrs
