# load and escape the string
FILE(READ "${INPUT_FILE}" INPUT_FILE_CONTENTS)
STRING(REPLACE "\\" "\\\\" INPUT_FILE_CONTENTS "${INPUT_FILE_CONTENTS}")
STRING(REPLACE "\"" "\\\"" INPUT_FILE_CONTENTS "${INPUT_FILE_CONTENTS}")
STRING(REGEX REPLACE "[\n\r]+" "\\\\n\"\n\"" INPUT_FILE_CONTENTS "${INPUT_FILE_CONTENTS}")

# configure the string
FILE(READ "${ESCAPE_TEMPLATE}" ESCAPE_TEMPLATE)
STRING(CONFIGURE "${ESCAPE_TEMPLATE}" ESCAPE_TEMPLATE @ONLY)

# write the output file
FILE(WRITE "${OUTPUT_FILE}" "${ESCAPE_TEMPLATE}")
