/* Copyright (C) 2010-2023 by Arm Limited. All rights reserved. */

#ifndef GATORCLIFLAGS_H_
#define GATORCLIFLAGS_H_

enum {
    USE_CMDLINE_ARG_SAMPLE_RATE = (1 << 0),
    USE_CMDLINE_ARG_CAPTURE_WORKING_DIR = (1 << 1),
    USE_CMDLINE_ARG_CAPTURE_COMMAND = (1 << 2),
    USE_CMDLINE_ARG_STOP_GATOR = (1 << 3),
    USE_CMDLINE_ARG_CALL_STACK_UNWINDING = (1 << 4),
    USE_CMDLINE_ARG_DURATION = (1 << 5),
    USE_CMDLINE_ARG_FTRACE_RAW = (1 << 6),
    USE_CMDLINE_ARG_EXCLUDE_KERNEL = (1 << 7),
    USE_CMDLINE_ARG_SMMU_MODEL = (1 << 8),
    USE_CMDLINE_ARG_IIDR_NUMBER = (1 << 9),
    USE_CMDLINE_ARG_OFF_CPU_PROFILING = (1 << 10),
};

#endif /* GATORCLIFLAGS_H_ */
