SET(BOOST_FILESYSTEM_DISABLE_COPY_FILE_RANGE ON)
SET(BOOST_FILESYSTEM_DISABLE_COPY_FILE_RANGE ON PARENT_SCOPE)
SET(BOOST_FILESYSTEM_DISABLE_COPY_FILE_RANGE ON CACHE BOOL "" FORCE)

SET(BOOST_FILESYSTEM_DISABLE_STATX ON)
SET(BOOST_FILESYSTEM_DISABLE_STATX ON PARENT_SCOPE)
SET(BOOST_FILESYSTEM_DISABLE_STATX ON CACHE BOOL "" FORCE)

SET(BOOST_FILESYSTEM_DISABLE_GETRANDOM ON)
SET(BOOST_FILESYSTEM_DISABLE_GETRANDOM ON PARENT_SCOPE)
SET(BOOST_FILESYSTEM_DISABLE_GETRANDOM ON CACHE BOOL "" FORCE)

LIST(APPEND B2_OPTIONS
    define=BOOST_FILESYSTEM_DISABLE_COPY_FILE_RANGE
    define=BOOST_FILESYSTEM_DISABLE_STATX
    define=BOOST_FILESYSTEM_DISABLE_GETRANDOM
)

