#!/bin/bash

set -eu

__rev=${1}
__commit_msg_file=commit-msg

trap "rm -f ${__commit_msg_file}" EXIT
git rev-list --format=%B --max-count=1 ${__rev} | tail -n+2 > ${__commit_msg_file}
pre-commit run commitlint --hook-stage commit-msg --commit-msg-filename ${__commit_msg_file}
