FIND_PROGRAM(CMAKE_ADDR2LINE    NAMES   "${CROSS_COMPILE}addr2line"     REQUIRED)
FIND_PROGRAM(CMAKE_AR           NAMES   "${CROSS_COMPILE}gcc-ar"
                                        "${CROSS_COMPILE}ar"            REQUIRED)
FIND_PROGRAM(CMAKE_LINKER       NAMES   "${CROSS_COMPILE}ld.gold"
                                        "${CROSS_COMPILE}ld"            REQUIRED)
FIND_PROGRAM(CMAKE_NM           NAMES   "${CROSS_COMPILE}gcc-nm"
                                        "${CROSS_COMPILE}nm"            REQUIRED)
FIND_PROGRAM(CMAKE_OBJCOPY      NAMES   "${CROSS_COMPILE}objcopy"       REQUIRED)
FIND_PROGRAM(CMAKE_OBJDUMP      NAMES   "${CROSS_COMPILE}objdump"       REQUIRED)
FIND_PROGRAM(CMAKE_RANLIB       NAMES   "${CROSS_COMPILE}gcc-ranlib"
                                        "${CROSS_COMPILE}ranlib"        REQUIRED)
FIND_PROGRAM(CMAKE_READELF      NAMES   "${CROSS_COMPILE}readelf"       REQUIRED)
FIND_PROGRAM(CMAKE_STRIP        NAMES   "${CROSS_COMPILE}strip"         REQUIRED)

FIND_PROGRAM(CMAKE_C_COMPILER           NAMES   "${CROSS_COMPILE}gcc"   REQUIRED)
FIND_PROGRAM(CMAKE_C_COMPILER_AR        NAMES   "${CROSS_COMPILE}gcc-ar")
FIND_PROGRAM(CMAKE_C_COMPILER_NM        NAMES   "${CROSS_COMPILE}gcc-nm")
FIND_PROGRAM(CMAKE_C_COMPILER_RANLIB    NAMES   "${CROSS_COMPILE}gcc-ranlib")
FIND_PROGRAM(CMAKE_CXX_COMPILER         NAMES   "${CROSS_COMPILE}g++"   REQUIRED)
FIND_PROGRAM(CMAKE_CXX_COMPILER_AR      NAMES   "${CROSS_COMPILE}gcc-ar")
FIND_PROGRAM(CMAKE_CXX_COMPILER_NM      NAMES   "${CROSS_COMPILE}gcc-nm")
FIND_PROGRAM(CMAKE_CXX_COMPILER_RANLIB  NAMES   "${CROSS_COMPILE}gcc-ranlib")
